### PR TITLE
add is-subnet and is-private-ip operators, test, docs. closes #14

### LINKED ISSUE #14: Feature: Add Operation for CIDR Calculations
Add an `is-subnet` operator that can determine whether or not the value is a member of a given network. 

This will be used to allow our Terraform SCA to check security group rules are within RFC1918 ranges.

Example:
```  
...
  - id: SG1
    resource: aws_security_group
    message: Security group should not allow ingress from 0.0.0.0/0
    severity: FAILURE
    assertions:
      - key: "ingress[].cidr_blocks[] | [*]"
        op: is-subnet
        value: "10.0.0.0/8"
...
```

I am happy to implement this. Do you have any reqs for the design? Otherwise I can submit a PR for review. @lhitchon @jeffb4

### PR DESCRIPTION
**Pull request by rmorris1218**

### CODE REVIEW

**Comment by lhitchon** [comment]
This PR looks great to me.

**Comment by lhitchon** [comment]
@BrianJakovich Thanks for merging this. Somebody who is set up for development, and has write access to the repo still needs to run `make bumpversion` to release a new version with these changes

**Comment by lhitchon** [comment]
Actually, probably having `git` and `make` is  probably enough - clone the repo and run `make bumpversion` - That adds a new tag to the repo, and triggers a build on CircleCI, where the actual build and release work will be done.

**Comment by jeffb4** [comment]
Will do, Larry. And didn't realize you'd lost write permissions, added you back.

**Comment by jeffb4** [comment]
New release cut

**Pull request merged**
